server:
  port: 8081
  servlet-path: /quick

#DB Configuration:
spring:
  datasource:
    sht:
      driverClassName: com.mysql.jdbc.Driver
      url: jdbc:mysql://47.92.149.109:3306/sht_order?useUnicode=true&characterEncoding=utf-8
      username: root
      password: Trace!@#321
    center:
      driverClassName: com.mysql.jdbc.Driver
      url: jdbc:mysql://47.92.149.109:3306/assert?useUnicode=true&characterEncoding=utf-8
      username: root
      password: Trace!@#321
  #JPA Configuration:
  jpa:
    database: MySQL
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
      naming_strategy: org.hibernate.cfg.ImprovedNamingStrategy


#spring集成Mybatis环境
mybatis:
  #pojo别名扫描包
  type-aliases-package: com.dhj.demo.pojo.center,com.dhj.demo.pojo.sht
  #加载Mybatis映射文件
  mapper-locations: classpath:mapper/*/*.xml


#Redis
  redis:
    host: 127.0.0.1
    port: 6379

name: 杜华杰
#对象
person:
  sex: 男
  student:
    name: zhangsan
    age: 25
mobile: {name: xiaomi,color: red}

#集合&数组
city:
  - shanghai
  - beijing
  - guangzhou
#citys: [shanghan,beijing,guangzhou]

#集合&数组 里面是对象
student:
  - name: zhangsan
    age: 18
  - name: lisi
    age: 12
#students: [{name: zhangsan,age: 18},{name: lisi,age: 12}]

#Map配置
map:
  key1: value1
  key2: value2